# Generated by Django 6.0.1 on 2026-02-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
